INSERT INTO m_city (idx_m_region, "name") VALUES(1, 'KABUPATEN BENGKULU SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(1, 'KABUPATEN BENGKULU UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(1, 'KABUPATEN KAUR');
INSERT INTO m_city (idx_m_region, "name") VALUES(1, 'KABUPATEN BENGKULU TENGAH');
INSERT INTO m_city (idx_m_region, "name") VALUES(1, 'KOTA BENGKULU');
INSERT INTO m_city (idx_m_region, "name") VALUES(1, 'KABUPATEN SELUMA');
INSERT INTO m_city (idx_m_region, "name") VALUES(1, 'KABUPATEN MUKOMUKO');
INSERT INTO m_city (idx_m_region, "name") VALUES(1, 'KABUPATEN KEPAHIANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(1, 'KABUPATEN LEBONG');
INSERT INTO m_city (idx_m_region, "name") VALUES(1, 'KABUPATEN REJANG LEBONG');
INSERT INTO m_city (idx_m_region, "name") VALUES(2, 'KABUPATEN PANDEGLANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(2, 'KOTA TANGERANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(2, 'KABUPATEN LEBAK');
INSERT INTO m_city (idx_m_region, "name") VALUES(2, 'KABUPATEN SERANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(2, 'KOTA TANGERANG SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(2, 'KOTA CILEGON');
INSERT INTO m_city (idx_m_region, "name") VALUES(2, 'KABUPATEN TANGERANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(2, 'KOTA SERANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KABUPATEN PIDIE');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KOTA LHOKSEUMAWE');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KABUPATEN ACEH TIMUR');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KABUPATEN ACEH TENGAH');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KABUPATEN ACEH TAMIANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KOTA SUBULUSSALAM');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KABUPATEN PIDIE JAYA');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KABUPATEN SIMEULUE');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KABUPATEN ACEH BESAR');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KABUPATEN BIREUEN');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KABUPATEN ACEH TENGGARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KOTA SABANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KABUPATEN ACEH UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KABUPATEN NAGAN RAYA');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KABUPATEN BENER MERIAH');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KABUPATEN ACEH SINGKIL');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KABUPATEN ACEH SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KABUPATEN ACEH BARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KABUPATEN ACEH JAYA');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KABUPATEN ACEH BARAT DAYA');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KABUPATEN GAYO LUES');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KOTA LANGSA');
INSERT INTO m_city (idx_m_region, "name") VALUES(3, 'KOTA BANDA ACEH');
INSERT INTO m_city (idx_m_region, "name") VALUES(4, 'KABUPATEN KEPULAUAN SULA');
INSERT INTO m_city (idx_m_region, "name") VALUES(4, 'KABUPATEN HALMAHERA TENGAH');
INSERT INTO m_city (idx_m_region, "name") VALUES(4, 'KOTA TERNATE');
INSERT INTO m_city (idx_m_region, "name") VALUES(4, 'KABUPATEN HALMAHERA TIMUR');
INSERT INTO m_city (idx_m_region, "name") VALUES(4, 'KABUPATEN PULAU MOROTAI');
INSERT INTO m_city (idx_m_region, "name") VALUES(4, 'KABUPATEN PULAU TALIABU');
INSERT INTO m_city (idx_m_region, "name") VALUES(4, 'KOTA TIDORE KEPULAUAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(4, 'KABUPATEN HALMAHERA UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(4, 'KABUPATEN HALMAHERA BARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(4, 'KABUPATEN HALMAHERA SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(5, 'KABUPATEN KETAPANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(5, 'KABUPATEN KUBU RAYA');
INSERT INTO m_city (idx_m_region, "name") VALUES(5, 'KABUPATEN KAPUAS HULU');
INSERT INTO m_city (idx_m_region, "name") VALUES(5, 'KABUPATEN SAMBAS');
INSERT INTO m_city (idx_m_region, "name") VALUES(5, 'KABUPATEN BENGKAYANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(5, 'KABUPATEN SEKADAU');
INSERT INTO m_city (idx_m_region, "name") VALUES(5, 'KABUPATEN SINTANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(5, 'KABUPATEN SANGGAU');
INSERT INTO m_city (idx_m_region, "name") VALUES(5, 'KABUPATEN LANDAK');
INSERT INTO m_city (idx_m_region, "name") VALUES(5, 'KOTA SINGKAWANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(5, 'KABUPATEN KAYONG UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(5, 'KABUPATEN MEMPAWAH');
INSERT INTO m_city (idx_m_region, "name") VALUES(5, 'KOTA PONTIANAK');
INSERT INTO m_city (idx_m_region, "name") VALUES(5, 'KABUPATEN MELAWI');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN BREBES');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN PEMALANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KOTA PEKALONGAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN SUKOHARJO');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN PURWOREJO');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN TEMANGGUNG');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN TEGAL');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN KENDAL');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN BOYOLALI');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN PEKALONGAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KOTA SALATIGA');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN SEMARANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN KEBUMEN');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN PATI');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN GROBOGAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KOTA SEMARANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KOTA TEGAL');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN JEPARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN REMBANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN KARANGANYAR');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN PURBALINGGA');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN MAGELANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN BATANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN BANJARNEGARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN BLORA');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN KLATEN');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN WONOGIRI');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KOTA SURAKARTA');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN SRAGEN');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN KUDUS');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN BANYUMAS');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN WONOSOBO');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KOTA MAGELANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN CILACAP');
INSERT INTO m_city (idx_m_region, "name") VALUES(6, 'KABUPATEN DEMAK');
INSERT INTO m_city (idx_m_region, "name") VALUES(7, 'KOTA JAKARTA BARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(7, 'KOTA JAKARTA TIMUR');
INSERT INTO m_city (idx_m_region, "name") VALUES(7, 'KOTA JAKARTA UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(7, 'KOTA JAKARTA SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(7, 'KABUPATEN KEPULAUAN SERIBU');
INSERT INTO m_city (idx_m_region, "name") VALUES(7, 'KOTA JAKARTA PUSAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(8, 'KOTA PALU');
INSERT INTO m_city (idx_m_region, "name") VALUES(8, 'KABUPATEN SIGI');
INSERT INTO m_city (idx_m_region, "name") VALUES(8, 'KABUPATEN BANGGAI LAUT');
INSERT INTO m_city (idx_m_region, "name") VALUES(8, 'KABUPATEN MOROWALI UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(8, 'KABUPATEN TOLI-TOLI');
INSERT INTO m_city (idx_m_region, "name") VALUES(8, 'KABUPATEN MOROWALI');
INSERT INTO m_city (idx_m_region, "name") VALUES(8, 'KABUPATEN TOJO UNA-UNA');
INSERT INTO m_city (idx_m_region, "name") VALUES(8, 'KABUPATEN BANGGAI KEPULAUAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(8, 'KABUPATEN BUOL');
INSERT INTO m_city (idx_m_region, "name") VALUES(8, 'KABUPATEN BANGGAI');
INSERT INTO m_city (idx_m_region, "name") VALUES(8, 'KABUPATEN PARIGI MOUTONG');
INSERT INTO m_city (idx_m_region, "name") VALUES(8, 'KABUPATEN POSO');
INSERT INTO m_city (idx_m_region, "name") VALUES(8, 'KABUPATEN DONGGALA');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN TIMOR TENGAH SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN SUMBA BARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KOTA KUPANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN SUMBA BARAT DAYA');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN ENDE');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN SIKKA');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN MANGGARAI BARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN MALAKA');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN NGADA');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN SUMBA TIMUR');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN KUPANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN NAGEKEO');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN MANGGARAI');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN ALOR');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN SUMBA TENGAH');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN TIMOR TENGAH UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN ROTE NDAO');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN MANGGARAI TIMUR');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN SABU RAIJUA');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN BELU');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN FLORES TIMUR');
INSERT INTO m_city (idx_m_region, "name") VALUES(9, 'KABUPATEN LEMBATA');
INSERT INTO m_city (idx_m_region, "name") VALUES(10, 'KABUPATEN TULANGBAWANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(10, 'KOTA METRO');
INSERT INTO m_city (idx_m_region, "name") VALUES(10, 'KABUPATEN TULANG BAWANG BARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(10, 'KABUPATEN PESISIR BARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(10, 'KABUPATEN WAY KANAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(10, 'KABUPATEN LAMPUNG SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(10, 'KOTA BANDAR LAMPUNG');
INSERT INTO m_city (idx_m_region, "name") VALUES(10, 'KABUPATEN PESAWARAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(10, 'KABUPATEN MESUJI');
INSERT INTO m_city (idx_m_region, "name") VALUES(10, 'KABUPATEN LAMPUNG UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(10, 'KABUPATEN LAMPUNG BARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(10, 'KABUPATEN LAMPUNG TENGAH');
INSERT INTO m_city (idx_m_region, "name") VALUES(10, 'KABUPATEN LAMPUNG TIMUR');
INSERT INTO m_city (idx_m_region, "name") VALUES(10, 'KABUPATEN TANGGAMUS');
INSERT INTO m_city (idx_m_region, "name") VALUES(10, 'KABUPATEN PRINGSEWU');
INSERT INTO m_city (idx_m_region, "name") VALUES(11, 'KABUPATEN KARANG ASEM');
INSERT INTO m_city (idx_m_region, "name") VALUES(11, 'KABUPATEN BADUNG');
INSERT INTO m_city (idx_m_region, "name") VALUES(11, 'KABUPATEN JEMBRANA');
INSERT INTO m_city (idx_m_region, "name") VALUES(11, 'KABUPATEN BULELENG');
INSERT INTO m_city (idx_m_region, "name") VALUES(11, 'KOTA DENPASAR');
INSERT INTO m_city (idx_m_region, "name") VALUES(11, 'KABUPATEN TABANAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(11, 'KABUPATEN BANGLI');
INSERT INTO m_city (idx_m_region, "name") VALUES(11, 'KABUPATEN KLUNGKUNG');
INSERT INTO m_city (idx_m_region, "name") VALUES(11, 'KABUPATEN GIANYAR');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KABUPATEN INDRAMAYU');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KABUPATEN KARAWANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KOTA BEKASI');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KOTA DEPOK');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KOTA BANJAR');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KABUPATEN GARUT');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KABUPATEN BANDUNG');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KABUPATEN SUBANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KABUPATEN CIREBON');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KABUPATEN TASIKMALAYA');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KABUPATEN MAJALENGKA');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KABUPATEN CIANJUR');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KABUPATEN SUMEDANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KOTA CIREBON');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KOTA CIMAHI');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KOTA TASIKMALAYA');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KABUPATEN KUNINGAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KABUPATEN PURWAKARTA');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KOTA BANDUNG');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KABUPATEN CIAMIS');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KABUPATEN BEKASI');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KOTA SUKABUMI');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KABUPATEN SUKABUMI');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KABUPATEN BANDUNG BARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KABUPATEN PANGANDARAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KOTA BOGOR');
INSERT INTO m_city (idx_m_region, "name") VALUES(12, 'KABUPATEN BOGOR');
INSERT INTO m_city (idx_m_region, "name") VALUES(13, 'KABUPATEN BIMA');
INSERT INTO m_city (idx_m_region, "name") VALUES(13, 'KABUPATEN LOMBOK TENGAH');
INSERT INTO m_city (idx_m_region, "name") VALUES(13, 'KABUPATEN LOMBOK TIMUR');
INSERT INTO m_city (idx_m_region, "name") VALUES(13, 'KOTA MATARAM');
INSERT INTO m_city (idx_m_region, "name") VALUES(13, 'KOTA BIMA');
INSERT INTO m_city (idx_m_region, "name") VALUES(13, 'KABUPATEN DOMPU');
INSERT INTO m_city (idx_m_region, "name") VALUES(13, 'KABUPATEN LOMBOK UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(13, 'KABUPATEN LOMBOK BARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(13, 'KABUPATEN SUMBAWA');
INSERT INTO m_city (idx_m_region, "name") VALUES(13, 'KABUPATEN SUMBAWA BARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(14, 'KABUPATEN HULU SUNGAI SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(14, 'KABUPATEN TAPIN');
INSERT INTO m_city (idx_m_region, "name") VALUES(14, 'KABUPATEN TANAH LAUT');
INSERT INTO m_city (idx_m_region, "name") VALUES(14, 'KABUPATEN TANAH BUMBU');
INSERT INTO m_city (idx_m_region, "name") VALUES(14, 'KOTA BANJARMASIN');
INSERT INTO m_city (idx_m_region, "name") VALUES(14, 'KABUPATEN BALANGAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(14, 'KOTA BANJAR BARU');
INSERT INTO m_city (idx_m_region, "name") VALUES(14, 'KABUPATEN BARITO KUALA');
INSERT INTO m_city (idx_m_region, "name") VALUES(14, 'KABUPATEN KOTA BARU');
INSERT INTO m_city (idx_m_region, "name") VALUES(14, 'KABUPATEN TABALONG');
INSERT INTO m_city (idx_m_region, "name") VALUES(14, 'KABUPATEN BANJAR');
INSERT INTO m_city (idx_m_region, "name") VALUES(14, 'KABUPATEN HULU SUNGAI TENGAH');
INSERT INTO m_city (idx_m_region, "name") VALUES(14, 'KABUPATEN HULU SUNGAI UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(15, 'KABUPATEN KULON PROGO');
INSERT INTO m_city (idx_m_region, "name") VALUES(15, 'KABUPATEN GUNUNG KIDUL');
INSERT INTO m_city (idx_m_region, "name") VALUES(15, 'KABUPATEN BANTUL');
INSERT INTO m_city (idx_m_region, "name") VALUES(15, 'KABUPATEN SLEMAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(15, 'KOTA YOGYAKARTA');
INSERT INTO m_city (idx_m_region, "name") VALUES(16, 'KABUPATEN KERINCI');
INSERT INTO m_city (idx_m_region, "name") VALUES(16, 'KABUPATEN MUARO JAMBI');
INSERT INTO m_city (idx_m_region, "name") VALUES(16, 'KABUPATEN TANJUNG JABUNG TIMUR');
INSERT INTO m_city (idx_m_region, "name") VALUES(16, 'KABUPATEN TANJUNG JABUNG BARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(16, 'KABUPATEN BATANG HARI');
INSERT INTO m_city (idx_m_region, "name") VALUES(16, 'KABUPATEN MERANGIN');
INSERT INTO m_city (idx_m_region, "name") VALUES(16, 'KOTA JAMBI');
INSERT INTO m_city (idx_m_region, "name") VALUES(16, 'KABUPATEN SAROLANGUN');
INSERT INTO m_city (idx_m_region, "name") VALUES(16, 'KABUPATEN BUNGO');
INSERT INTO m_city (idx_m_region, "name") VALUES(16, 'KABUPATEN TEBO');
INSERT INTO m_city (idx_m_region, "name") VALUES(16, 'KOTA SUNGAI PENUH');
INSERT INTO m_city (idx_m_region, "name") VALUES(17, 'KABUPATEN SERAM BAGIAN BARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(17, 'KABUPATEN MALUKU BARAT DAYA');
INSERT INTO m_city (idx_m_region, "name") VALUES(17, 'KABUPATEN SERAM BAGIAN TIMUR');
INSERT INTO m_city (idx_m_region, "name") VALUES(17, 'KABUPATEN MALUKU TENGGARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(17, 'KABUPATEN BURU');
INSERT INTO m_city (idx_m_region, "name") VALUES(17, 'KABUPATEN BURU SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(17, 'KABUPATEN KEPULAUAN ARU');
INSERT INTO m_city (idx_m_region, "name") VALUES(17, 'KOTA AMBON');
INSERT INTO m_city (idx_m_region, "name") VALUES(17, 'KOTA TUAL');
INSERT INTO m_city (idx_m_region, "name") VALUES(17, 'KABUPATEN MALUKU TENGGARA BARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(17, 'KABUPATEN MALUKU TENGAH');
INSERT INTO m_city (idx_m_region, "name") VALUES(18, 'KABUPATEN KOLAKA');
INSERT INTO m_city (idx_m_region, "name") VALUES(18, 'KOTA KENDARI');
INSERT INTO m_city (idx_m_region, "name") VALUES(18, 'KABUPATEN KONAWE UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(18, 'KABUPATEN BUTON SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(18, 'KABUPATEN MUNA BARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(18, 'KABUPATEN KOLAKA UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(18, 'KABUPATEN BUTON UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(18, 'KABUPATEN MUNA');
INSERT INTO m_city (idx_m_region, "name") VALUES(18, 'KABUPATEN KONAWE KEPULAUAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(18, 'KABUPATEN BUTON TENGAH');
INSERT INTO m_city (idx_m_region, "name") VALUES(18, 'KABUPATEN BUTON');
INSERT INTO m_city (idx_m_region, "name") VALUES(18, 'KABUPATEN KOLAKA TIMUR');
INSERT INTO m_city (idx_m_region, "name") VALUES(18, 'KOTA BAUBAU');
INSERT INTO m_city (idx_m_region, "name") VALUES(18, 'KABUPATEN KONAWE SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(18, 'KABUPATEN WAKATOBI');
INSERT INTO m_city (idx_m_region, "name") VALUES(18, 'KABUPATEN BOMBANA');
INSERT INTO m_city (idx_m_region, "name") VALUES(18, 'KABUPATEN KONAWE');
INSERT INTO m_city (idx_m_region, "name") VALUES(19, 'KABUPATEN GORONTALO UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(19, 'KABUPATEN BOALEMO');
INSERT INTO m_city (idx_m_region, "name") VALUES(19, 'KABUPATEN POHUWATO');
INSERT INTO m_city (idx_m_region, "name") VALUES(19, 'KOTA GORONTALO');
INSERT INTO m_city (idx_m_region, "name") VALUES(19, 'KABUPATEN GORONTALO');
INSERT INTO m_city (idx_m_region, "name") VALUES(19, 'KABUPATEN BONE BOLANGO');
INSERT INTO m_city (idx_m_region, "name") VALUES(20, 'KOTA LUBUKLINGGAU');
INSERT INTO m_city (idx_m_region, "name") VALUES(20, 'KOTA PALEMBANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(20, 'KABUPATEN OGAN KOMERING ULU');
INSERT INTO m_city (idx_m_region, "name") VALUES(20, 'KOTA PAGAR ALAM');
INSERT INTO m_city (idx_m_region, "name") VALUES(20, 'KABUPATEN MUSI RAWAS UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(20, 'KABUPATEN LAHAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(20, 'KABUPATEN PENUKAL ABAB LEMATANG ILIR');
INSERT INTO m_city (idx_m_region, "name") VALUES(20, 'KABUPATEN BANYU ASIN');
INSERT INTO m_city (idx_m_region, "name") VALUES(20, 'KABUPATEN MUSI RAWAS');
INSERT INTO m_city (idx_m_region, "name") VALUES(20, 'KABUPATEN MUARA ENIM');
INSERT INTO m_city (idx_m_region, "name") VALUES(20, 'KABUPATEN EMPAT LAWANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(20, 'KABUPATEN OGAN KOMERING ULU TIMUR');
INSERT INTO m_city (idx_m_region, "name") VALUES(20, 'KABUPATEN OGAN ILIR');
INSERT INTO m_city (idx_m_region, "name") VALUES(20, 'KABUPATEN OGAN KOMERING ILIR');
INSERT INTO m_city (idx_m_region, "name") VALUES(20, 'KABUPATEN MUSI BANYUASIN');
INSERT INTO m_city (idx_m_region, "name") VALUES(20, 'KABUPATEN OGAN KOMERING ULU SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(20, 'KOTA PRABUMULIH');
INSERT INTO m_city (idx_m_region, "name") VALUES(21, 'KABUPATEN MALINAU');
INSERT INTO m_city (idx_m_region, "name") VALUES(21, 'KOTA TARAKAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(21, 'KABUPATEN BULUNGAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(21, 'KABUPATEN NUNUKAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(21, 'KABUPATEN TANA TIDUNG');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN SUMENEP');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN KEDIRI');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN BANYUWANGI');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN MALANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KOTA MALANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KOTA SURABAYA');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KOTA BATU');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN LUMAJANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KOTA PASURUAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN JOMBANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN MADIUN');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN PASURUAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN SITUBONDO');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN BOJONEGORO');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN BANGKALAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KOTA PROBOLINGGO');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN MOJOKERTO');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KOTA BLITAR');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN NGAWI');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KOTA KEDIRI');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN JEMBER');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN SIDOARJO');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN TUBAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN PAMEKASAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN LAMONGAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN MAGETAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN PONOROGO');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN NGANJUK');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KOTA MADIUN');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN SAMPANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN PROBOLINGGO');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN PACITAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN BONDOWOSO');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KOTA MOJOKERTO');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN GRESIK');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN BLITAR');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN TRENGGALEK');
INSERT INTO m_city (idx_m_region, "name") VALUES(22, 'KABUPATEN TULUNGAGUNG');
INSERT INTO m_city (idx_m_region, "name") VALUES(23, 'KABUPATEN SERUYAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(23, 'KABUPATEN GUNUNG MAS');
INSERT INTO m_city (idx_m_region, "name") VALUES(23, 'KABUPATEN MURUNG RAYA');
INSERT INTO m_city (idx_m_region, "name") VALUES(23, 'KABUPATEN KOTAWARINGIN BARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(23, 'KABUPATEN SUKAMARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(23, 'KOTA PALANGKA RAYA');
INSERT INTO m_city (idx_m_region, "name") VALUES(23, 'KABUPATEN BARITO TIMUR');
INSERT INTO m_city (idx_m_region, "name") VALUES(23, 'KABUPATEN LAMANDAU');
INSERT INTO m_city (idx_m_region, "name") VALUES(23, 'KABUPATEN KATINGAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(23, 'KABUPATEN KAPUAS');
INSERT INTO m_city (idx_m_region, "name") VALUES(23, 'KABUPATEN PULANG PISAU');
INSERT INTO m_city (idx_m_region, "name") VALUES(23, 'KABUPATEN BARITO UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(23, 'KABUPATEN KOTAWARINGIN TIMUR');
INSERT INTO m_city (idx_m_region, "name") VALUES(23, 'KABUPATEN BARITO SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(24, 'KABUPATEN POLEWALI MANDAR');
INSERT INTO m_city (idx_m_region, "name") VALUES(24, 'KABUPATEN MAMUJU TENGAH');
INSERT INTO m_city (idx_m_region, "name") VALUES(24, 'KABUPATEN MAJENE');
INSERT INTO m_city (idx_m_region, "name") VALUES(24, 'KABUPATEN MAMUJU UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(24, 'KABUPATEN MAMASA');
INSERT INTO m_city (idx_m_region, "name") VALUES(24, 'KABUPATEN MAMUJU');
INSERT INTO m_city (idx_m_region, "name") VALUES(25, 'KABUPATEN BINTAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(25, 'KOTA TANJUNG PINANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(25, 'KABUPATEN NATUNA');
INSERT INTO m_city (idx_m_region, "name") VALUES(25, 'KOTA B A T A M');
INSERT INTO m_city (idx_m_region, "name") VALUES(25, 'KABUPATEN KARIMUN');
INSERT INTO m_city (idx_m_region, "name") VALUES(25, 'KABUPATEN KEPULAUAN ANAMBAS');
INSERT INTO m_city (idx_m_region, "name") VALUES(25, 'KABUPATEN LINGGA');
INSERT INTO m_city (idx_m_region, "name") VALUES(26, 'KABUPATEN PELALAWAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(26, 'KABUPATEN KEPULAUAN MERANTI');
INSERT INTO m_city (idx_m_region, "name") VALUES(26, 'KABUPATEN INDRAGIRI HILIR');
INSERT INTO m_city (idx_m_region, "name") VALUES(26, 'KABUPATEN KAMPAR');
INSERT INTO m_city (idx_m_region, "name") VALUES(26, 'KOTA PEKANBARU');
INSERT INTO m_city (idx_m_region, "name") VALUES(26, 'KOTA D U M A I');
INSERT INTO m_city (idx_m_region, "name") VALUES(26, 'KABUPATEN BENGKALIS');
INSERT INTO m_city (idx_m_region, "name") VALUES(26, 'KABUPATEN S I A K');
INSERT INTO m_city (idx_m_region, "name") VALUES(26, 'KABUPATEN INDRAGIRI HULU');
INSERT INTO m_city (idx_m_region, "name") VALUES(26, 'KABUPATEN KUANTAN SINGINGI');
INSERT INTO m_city (idx_m_region, "name") VALUES(26, 'KABUPATEN ROKAN HILIR');
INSERT INTO m_city (idx_m_region, "name") VALUES(26, 'KABUPATEN ROKAN HULU');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN SAMOSIR');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN SERDANG BEDAGAI');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN TAPANULI SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KOTA GUNUNGSITOLI');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN LANGKAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KOTA TEBING TINGGI');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN PADANG LAWAS UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KOTA PEMATANG SIANTAR');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KOTA BINJAI');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KOTA PADANGSIDIMPUAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN LABUHAN BATU');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN BATU BARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN LABUHAN BATU UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN TAPANULI UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN LABUHAN BATU SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN PAKPAK BHARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN MANDAILING NATAL');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN TOBA SAMOSIR');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KOTA MEDAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KOTA TANJUNG BALAI');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN DELI SERDANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN NIAS BARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN DAIRI');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN KARO');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN NIAS');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN SIMALUNGUN');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN ASAHAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN PADANG LAWAS');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KOTA SIBOLGA');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN NIAS UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN NIAS SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN TAPANULI TENGAH');
INSERT INTO m_city (idx_m_region, "name") VALUES(27, 'KABUPATEN HUMBANG HASUNDUTAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(28, 'KABUPATEN KUTAI BARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(28, 'KOTA BALIKPAPAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(28, 'KOTA BONTANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(28, 'KABUPATEN PASER');
INSERT INTO m_city (idx_m_region, "name") VALUES(28, 'KABUPATEN KUTAI KARTANEGARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(28, 'KABUPATEN BERAU');
INSERT INTO m_city (idx_m_region, "name") VALUES(28, 'KOTA SAMARINDA');
INSERT INTO m_city (idx_m_region, "name") VALUES(28, 'KABUPATEN KUTAI TIMUR');
INSERT INTO m_city (idx_m_region, "name") VALUES(28, 'KABUPATEN PENAJAM PASER UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(28, 'KABUPATEN MAHAKAM HULU');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KOTA PAREPARE');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN GOWA');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN LUWU TIMUR');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN PINRANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN MAROS');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN TANA TORAJA');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN SIDENRENG RAPPANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN WAJO');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN BANTAENG');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN BULUKUMBA');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN SINJAI');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN TORAJA UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN LUWU');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN PANGKAJENE DAN KEPULAUAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN ENREKANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN TAKALAR');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN BONE');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN BARRU');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN LUWU UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KOTA MAKASSAR');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN KEPULAUAN SELAYAR');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN SOPPENG');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KOTA PALOPO');
INSERT INTO m_city (idx_m_region, "name") VALUES(29, 'KABUPATEN JENEPONTO');
INSERT INTO m_city (idx_m_region, "name") VALUES(30, 'KABUPATEN BANGKA TENGAH');
INSERT INTO m_city (idx_m_region, "name") VALUES(30, 'KABUPATEN BELITUNG');
INSERT INTO m_city (idx_m_region, "name") VALUES(30, 'KABUPATEN BELITUNG TIMUR');
INSERT INTO m_city (idx_m_region, "name") VALUES(30, 'KABUPATEN BANGKA BARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(30, 'KABUPATEN BANGKA');
INSERT INTO m_city (idx_m_region, "name") VALUES(30, 'KOTA PANGKAL PINANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(30, 'KABUPATEN BANGKA SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(31, 'KOTA SOLOK');
INSERT INTO m_city (idx_m_region, "name") VALUES(31, 'KOTA PAYAKUMBUH');
INSERT INTO m_city (idx_m_region, "name") VALUES(31, 'KABUPATEN SOLOK SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(31, 'KABUPATEN SOLOK');
INSERT INTO m_city (idx_m_region, "name") VALUES(31, 'KABUPATEN AGAM');
INSERT INTO m_city (idx_m_region, "name") VALUES(31, 'KABUPATEN PASAMAN BARAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(31, 'KABUPATEN PASAMAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(31, 'KOTA PARIAMAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(31, 'KOTA PADANG PANJANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(31, 'KOTA PADANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(31, 'KABUPATEN PESISIR SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(31, 'KOTA SAWAH LUNTO');
INSERT INTO m_city (idx_m_region, "name") VALUES(31, 'KABUPATEN KEPULAUAN MENTAWAI');
INSERT INTO m_city (idx_m_region, "name") VALUES(31, 'KABUPATEN LIMA PULUH KOTA');
INSERT INTO m_city (idx_m_region, "name") VALUES(31, 'KABUPATEN DHARMASRAYA');
INSERT INTO m_city (idx_m_region, "name") VALUES(31, 'KABUPATEN PADANG PARIAMAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(31, 'KABUPATEN SIJUNJUNG');
INSERT INTO m_city (idx_m_region, "name") VALUES(31, 'KABUPATEN TANAH DATAR');
INSERT INTO m_city (idx_m_region, "name") VALUES(31, 'KOTA BUKITTINGGI');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN PUNCAK');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KOTA JAYAPURA');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN INTAN JAYA');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN MIMIKA');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN NDUGA');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN ASMAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN BIAK NUMFOR');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN BOVEN DIGOEL');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN NABIRE');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN KEEROM');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN PANIAI');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN WAROPEN');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN MAMBERAMO TENGAH');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN MERAUKE');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN MAMBERAMO RAYA');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN DEIYAI');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN LANNY JAYA');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN JAYAWIJAYA');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN JAYAPURA');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN MAPPI');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN SUPIORI');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN KEPULAUAN YAPEN');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN PEGUNUNGAN BINTANG');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN DOGIYAI');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN TOLIKARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN SARMI');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN YALIMO');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN PUNCAK JAYA');
INSERT INTO m_city (idx_m_region, "name") VALUES(32, 'KABUPATEN YAHUKIMO');
INSERT INTO m_city (idx_m_region, "name") VALUES(33, 'KABUPATEN PEGUNUNGAN ARFAK');
INSERT INTO m_city (idx_m_region, "name") VALUES(33, 'KABUPATEN SORONG SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(33, 'KOTA SORONG');
INSERT INTO m_city (idx_m_region, "name") VALUES(33, 'KABUPATEN KAIMANA');
INSERT INTO m_city (idx_m_region, "name") VALUES(33, 'KABUPATEN MANOKWARI');
INSERT INTO m_city (idx_m_region, "name") VALUES(33, 'KABUPATEN MAYBRAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(33, 'KABUPATEN SORONG');
INSERT INTO m_city (idx_m_region, "name") VALUES(33, 'KABUPATEN MANOKWARI SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(33, 'KABUPATEN RAJA AMPAT');
INSERT INTO m_city (idx_m_region, "name") VALUES(33, 'KABUPATEN TAMBRAUW');
INSERT INTO m_city (idx_m_region, "name") VALUES(33, 'KABUPATEN TELUK BINTUNI');
INSERT INTO m_city (idx_m_region, "name") VALUES(33, 'KABUPATEN FAKFAK');
INSERT INTO m_city (idx_m_region, "name") VALUES(33, 'KABUPATEN TELUK WONDAMA');
INSERT INTO m_city (idx_m_region, "name") VALUES(34, 'KOTA BITUNG');
INSERT INTO m_city (idx_m_region, "name") VALUES(34, 'KOTA TOMOHON');
INSERT INTO m_city (idx_m_region, "name") VALUES(34, 'KABUPATEN SIAU TAGULANDANG BIARO');
INSERT INTO m_city (idx_m_region, "name") VALUES(34, 'KABUPATEN KEPULAUAN SANGIHE');
INSERT INTO m_city (idx_m_region, "name") VALUES(34, 'KABUPATEN KEPULAUAN TALAUD');
INSERT INTO m_city (idx_m_region, "name") VALUES(34, 'KABUPATEN MINAHASA TENGGARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(34, 'KABUPATEN MINAHASA');
INSERT INTO m_city (idx_m_region, "name") VALUES(34, 'KABUPATEN MINAHASA SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(34, 'KABUPATEN BOLAANG MONGONDOW TIMUR');
INSERT INTO m_city (idx_m_region, "name") VALUES(34, 'KABUPATEN BOLAANG MONGONDOW UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(34, 'KABUPATEN BOLAANG MONGONDOW');
INSERT INTO m_city (idx_m_region, "name") VALUES(34, 'KABUPATEN MINAHASA UTARA');
INSERT INTO m_city (idx_m_region, "name") VALUES(34, 'KOTA MANADO');
INSERT INTO m_city (idx_m_region, "name") VALUES(34, 'KABUPATEN BOLAANG MONGONDOW SELATAN');
INSERT INTO m_city (idx_m_region, "name") VALUES(34, 'KOTA KOTAMOBAGU');
