INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(15, 'DI YOGYAKARTA', 'A', '1');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(7, 'DKI JAKARTA', 'A', '1');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(19, 'GORONTALO', 'A', '1');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(16, 'JAMBI', 'A', '1');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(12, 'JAWA BARAT', 'A', '1');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(5, 'KALIMANTAN BARAT', 'A', '1');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(21, 'KALIMANTAN UTARA', 'A', '1');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(30, 'KEPULAUAN BANGKA BELITUNG', 'A', '1');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(32, 'PAPUA', 'A', '1');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(8, 'SULAWESI TENGAH', 'A', '1');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(3, 'ACEH', 'A', '2');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(22, 'JAWA TIMUR', 'A', '2');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(28, 'KALIMANTAN TIMUR', 'A', '2');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(25, 'KEPULAUAN RIAU', 'A', '1');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(10, 'LAMPUNG', 'A', '2');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(17, 'MALUKU', 'A', '2');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(9, 'NUSA TENGGARA TIMUR', 'A', '2');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(33, 'PAPUA BARAT', 'A', '2');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(26, 'RIAU', 'A', '2');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(29, 'SULAWESI SELATAN', 'A', '2');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(18, 'SULAWESI TENGGARA', 'A', '2');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(31, 'SUMATERA BARAT', 'A', '2');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(20, 'SUMATERA SELATAN', 'A', '2');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(11, 'BALI', 'A', '3');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(2, 'BANTEN', 'A', '3');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(1, 'BENGKULU', 'A', '3');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(6, 'JAWA TENGAH', 'A', '3');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(14, 'KALIMANTAN SELATAN', 'A', '3');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(23, 'KALIMANTAN TENGAH', 'A', '3');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(4, 'MALUKU UTARA', 'A', '3');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(13, 'NUSA TENGGARA BARAT', 'A', '3');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(24, 'SULAWESI BARAT', 'A', '3');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(34, 'SULAWESI UTARA', 'A', '3');
INSERT INTO m_region (idx_m_region, "name", record_status, regional) VALUES(27, 'SUMATERA UTARA', 'A', '3');
